In [1]:
import torch
import pandas as pd 

dataset=pd.read_csv('Telco-Customer-Churn.csv')
# dataset.head()

In [2]:
dataset=dataset.drop(['customerID'],axis=1)
dataset.columns=dataset.columns.str.lower()
dataset.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 7043 entries, 0 to 7042
Data columns (total 20 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   gender            7043 non-null   object
 1   seniorcitizen     7043 non-null   int64
 2   partner           7043 non-null   object
 3   dependents        7043 non-null   object
 4   tenure            7043 non-null   int64
 5   phoneservice      7043 non-null   object
 6   multiplelines     7043 non-null   object
 7   internetservice   7043 non-null   object
 8   onlinesecurity    7043 non-null   object
 9   onlinebackup      7043 non-null   object
 10  deviceprotection  7043 non-null   object
 11  techsupport       7043 non-null   object
 12  streamingtv       7043 non-null   object
 13  streamingmovies   7043 non-null   object
 14  contract          7043 non-null   object
 15  paperlessbilling  7043 non-null   object
 16  paymentmethod     7043 non-null   object
 17  monthlycharges    7043 non-null   float64
 18  totalcharges      7043 non-null   object
 19  churn             7043 non-null   object
dtypes: float64(1), int64(2), object(17)
memory usage: 1.1+ MB

In [65]:
dataset.head()

,gender,seniorcitizen,partner,dependents,tenure,phoneservice,multiplelines,internetservice,onlinesecurity,onlinebackup,deviceprotection,techsupport,streamingtv,streamingmovies,contract,paperlessbilling,paymentmethod,monthlycharges,totalcharges,churn
0,Female,0,Yes,No,1,No,No phone service,DSL,No,Yes,No,No,No,No,Month-to-month,Yes,Electronic check,29.85,29.85,No
1,Male,0,No,No,34,Yes,No,DSL,Yes,No,Yes,No,No,No,One year,No,Mailed check,56.95,1889.5,No
2,Male,0,No,No,2,Yes,No,DSL,Yes,Yes,No,No,No,No,Month-to-month,Yes,Mailed check,53.85,108.15,Yes
3,Male,0,No,No,45,No,No phone service,DSL,Yes,No,Yes,Yes,No,No,One year,No,Bank transfer (automatic),42.30,1840.75,No
4,Female,0,No,No,2,Yes,No,Fiber optic,No,No,No,No,No,No,Month-to-month,Yes,Electronic check,70.70,151.65,Yes

In [3]:
dataset['gender']=dataset['gender'].map({ 'Male':1,'Female':0 })

In [4]:
from sklearn.preprocessing import LabelEncoder
labelencoder=LabelEncoder()
dataset['partner']=labelencoder.fit_transform(dataset['partner'])

In [5]:
columns=['dependents','phoneservice','multiplelines','paperlessbilling','churn']
for column in columns:
    dataset[column]=labelencoder.fit_transform(dataset[column])

In [6]:
from sklearn.preprocessing import OneHotEncoder 
encoder=OneHotEncoder(sparse_output=False)
internet=encoder.fit_transform(dataset[['internetservice']])
dataset=dataset.drop(['internetservice'],axis=1)
encoder.get_feature_names_out()
internetservice=pd.DataFrame(internet,columns=encoder.get_feature_names_out(['internetservice']))

In [7]:
dataset=pd.concat((dataset,internetservice),axis=1)
# dataset.head()

In [8]:
column=['onlinesecurity','onlinebackup','deviceprotection','techsupport','streamingtv','streamingmovies','contract','paymentmethod']
for col in column:
    colum=encoder.fit_transform(dataset[[col]])
    dataset=dataset.drop([col],axis=1)
    dataframe=pd.DataFrame(colum,columns=encoder.get_feature_names_out([col]))
    dataset=pd.concat((dataset,dataframe),axis=1)

In [72]:
for column in dataset.columns:
    print(column,dataset[column].nunique())

gender 2
seniorcitizen 2
partner 2
dependents 2
tenure 73
phoneservice 2
multiplelines 3
paperlessbilling 2
monthlycharges 1585
totalcharges 6531
churn 2
internetservice_DSL 2
internetservice_Fiber optic 2
internetservice_No 2
onlinesecurity_No 2
onlinesecurity_No internet service 2
onlinesecurity_Yes 2
onlinebackup_No 2
onlinebackup_No internet service 2
onlinebackup_Yes 2
deviceprotection_No 2
deviceprotection_No internet service 2
deviceprotection_Yes 2
techsupport_No 2
techsupport_No internet service 2
techsupport_Yes 2
streamingtv_No 2
streamingtv_No internet service 2
streamingtv_Yes 2
streamingmovies_No 2
streamingmovies_No internet service 2
streamingmovies_Yes 2
contract_Month-to-month 2
contract_One year 2
contract_Two year 2
paymentmethod_Bank transfer (automatic) 2
paymentmethod_Credit card (automatic) 2
paymentmethod_Electronic check 2
paymentmethod_Mailed check 2

In [73]:
dataset.head()

,gender,seniorcitizen,partner,dependents,tenure,phoneservice,multiplelines,paperlessbilling,monthlycharges,totalcharges,...,streamingmovies_No,streamingmovies_No internet service,streamingmovies_Yes,contract_Month-to-month,contract_One year,contract_Two year,paymentmethod_Bank transfer (automatic),paymentmethod_Credit card (automatic),paymentmethod_Electronic check,paymentmethod_Mailed check
0,0,0,1,0,1,0,1,1,29.85,29.85,...,1.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,1.0,0.0
1,1,0,0,0,34,1,0,0,56.95,1889.5,...,1.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,1.0
2,1,0,0,0,2,1,0,1,53.85,108.15,...,1.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,1.0
3,1,0,0,0,45,0,1,0,42.30,1840.75,...,1.0,0.0,0.0,0.0,1.0,0.0,1.0,0.0,0.0,0.0
4,0,0,0,0,2,1,0,1,70.70,151.65,...,1.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,1.0,0.0

In [9]:
import numpy as np
charges=['monthlycharges','totalcharges']
for charge in charges:
    dataset[charge]=pd.to_numeric(dataset[charge],errors='coerce')
    dataset[charge]=dataset[charge].replace(0,np.nan)
    dataset[charge]=dataset[charge].fillna(dataset[charge].median())
    # print(np.isnan(dataset[charge]).sum())

In [10]:
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler
ind_variable=dataset.drop('churn',axis=1)
dep_variable=dataset['churn']
scaler=StandardScaler()
x_train,x_test,y_train,y_test=train_test_split(ind_variable,
                                               dep_variable,
                                               test_size=0.2,
                                               random_state=42,
                                               stratify=dep_variable)
x_train=scaler.fit_transform(x_train)
x_test=scaler.fit_transform(x_test)
# print(np.isnan(x_train).sum())

In [15]:
import torch 
import torch.nn as nn 
import torch.optim as optim
class Model(nn.Module):
    def __init__(self):
        super().__init__()
        
        self.input=nn.Linear(38,64)
        self.relu=nn.ReLU()
        self.h1=nn.Linear(64,32)
        self.h2=nn.Linear(32,16)
        # self.h3=nn.Linear(32,16)
        self.output=nn.Linear(16,1)
        self.sigmoid=nn.Sigmoid()

    def forward(self,x):
        x=self.input(x)
        x=self.relu(x)
        x=self.h1(x)
        x=self.relu(x)
        x=self.h2(x)
        x=self.relu(x)
        # x=self.h3(x)
        # x=self.relu(x)
        x=self.output(x)
        x=self.sigmoid(x)
     
        return x

print('success')

success

In [ ]:
y_train=np.array(y_train)
y_test=np.array(y_test)

y_train=torch.tensor(y_train,dtype=torch.float32).reshape(-1,1)
y_test=torch.tensor(y_test,dtype=torch.float32).reshape(-1,1)
x_test=torch.tensor(x_test,dtype=torch.float32)
x_train=torch.tensor(x_train,dtype=torch.float32)

In [16]:


x_training,x_val,y_training,y_val=train_test_split(x_train,
                                                   y_train,
                                                   test_size=0.2,
                                                   random_state=42,
                                                   stratify=y_train)
                                                
                                             

model=Model()

criteria=nn.BCELoss()

optimizer=optim.Adam(
    model.parameters(),
    lr=0.001)

epochs=100

for epoch in range(epochs):
    predictions=model(x_training)
    loss=criteria(predictions,y_training)
    pred_prob=(predictions>0.4).float()
    accuracy=(pred_prob == y_training).float().mean()
    optimizer.zero_grad()

    loss.backward()
    optimizer.step()
    with torch.no_grad():
        validations=model(x_val)
        val_loss=criteria(validations,y_val)
        val_prob=(validations>0.4).float()
        val_accuracy=(val_prob==y_val).float().mean()
    print(f'Epoch:{epoch}   '
         f'Loss:{loss.item():.4f}  '
         f'Accuracy:{accuracy.item():.4f}  '
         f'Val_loss:{val_loss.item():.4f}  '
         f'Val_accuracy:{val_accuracy.item():.4f} ')

with torch.no_grad():
    final_prediction=model(x_test)
    final_loss=criteria(final_prediction,y_test)
    fin_prob=(final_prediction>0.4).float()
    final_accuracy=(fin_prob == y_test).float().mean()

    print(f'Test Loss: {final_loss.item():.4f}\n'
          f'Test Accuracy:{final_accuracy.item():.4f}')

Epoch:0   Loss:0.7490  Accuracy:0.2654  Val_loss:0.7428  Val_accuracy:0.2653
Epoch:1   Loss:0.7431  Accuracy:0.2654  Val_loss:0.7369  Val_accuracy:0.2653
Epoch:2   Loss:0.7372  Accuracy:0.2654  Val_loss:0.7308  Val_accuracy:0.2653
Epoch:3   Loss:0.7312  Accuracy:0.2654  Val_loss:0.7246  Val_accuracy:0.2653
Epoch:4   Loss:0.7250  Accuracy:0.2654  Val_loss:0.7182  Val_accuracy:0.2653
Epoch:5   Loss:0.7186  Accuracy:0.2654  Val_loss:0.7118  Val_accuracy:0.2653
Epoch:6   Loss:0.7123  Accuracy:0.2654  Val_loss:0.7053  Val_accuracy:0.2653
Epoch:7   Loss:0.7059  Accuracy:0.2654  Val_loss:0.6989  Val_accuracy:0.2653
Epoch:8   Loss:0.6996  Accuracy:0.2654  Val_loss:0.6924  Val_accuracy:0.2653
Epoch:9   Loss:0.6932  Accuracy:0.2654  Val_loss:0.6857  Val_accuracy:0.2653
Epoch:10   Loss:0.6865  Accuracy:0.2654  Val_loss:0.6788  Val_accuracy:0.2653
Epoch:11   Loss:0.6796  Accuracy:0.2654  Val_loss:0.6715  Val_accuracy:0.2653
Epoch:12   Loss:0.6723  Accuracy:0.2654  Val_loss:0.6638  Val_accuracy:0.2653
Epoch:13   Loss:0.6646  Accuracy:0.2654  Val_loss:0.6558  Val_accuracy:0.2653
Epoch:14   Loss:0.6566  Accuracy:0.2654  Val_loss:0.6475  Val_accuracy:0.2680
Epoch:15   Loss:0.6483  Accuracy:0.2663  Val_loss:0.6388  Val_accuracy:0.2831
Epoch:16   Loss:0.6396  Accuracy:0.2771  Val_loss:0.6297  Val_accuracy:0.3452
Epoch:17   Loss:0.6305  Accuracy:0.3481  Val_loss:0.6202  Val_accuracy:0.4508
Epoch:18   Loss:0.6211  Accuracy:0.4406  Val_loss:0.6104  Val_accuracy:0.5173
Epoch:19   Loss:0.6114  Accuracy:0.5105  Val_loss:0.6003  Val_accuracy:0.5608
Epoch:20   Loss:0.6013  Accuracy:0.5503  Val_loss:0.5898  Val_accuracy:0.5839
Epoch:21   Loss:0.5909  Accuracy:0.5767  Val_loss:0.5791  Val_accuracy:0.6167
Epoch:22   Loss:0.5803  Accuracy:0.6037  Val_loss:0.5681  Val_accuracy:0.6424
Epoch:23   Loss:0.5695  Accuracy:0.6288  Val_loss:0.5571  Val_accuracy:0.6619
Epoch:24   Loss:0.5586  Accuracy:0.6550  Val_loss:0.5460  Val_accuracy:0.6752
Epoch:25   Loss:0.5478  Accuracy:0.6836  Val_loss:0.5352  Val_accuracy:0.6921
Epoch:26   Loss:0.5371  Accuracy:0.7036  Val_loss:0.5246  Val_accuracy:0.7045
Epoch:27   Loss:0.5268  Accuracy:0.7202  Val_loss:0.5144  Val_accuracy:0.7214
Epoch:28   Loss:0.5169  Accuracy:0.7333  Val_loss:0.5048  Val_accuracy:0.7365
Epoch:29   Loss:0.5075  Accuracy:0.7451  Val_loss:0.4957  Val_accuracy:0.7498
Epoch:30   Loss:0.4987  Accuracy:0.7535  Val_loss:0.4874  Val_accuracy:0.7595
Epoch:31   Loss:0.4907  Accuracy:0.7599  Val_loss:0.4799  Val_accuracy:0.7631
Epoch:32   Loss:0.4834  Accuracy:0.7661  Val_loss:0.4732  Val_accuracy:0.7684
Epoch:33   Loss:0.4769  Accuracy:0.7739  Val_loss:0.4674  Val_accuracy:0.7764
Epoch:34   Loss:0.4713  Accuracy:0.7779  Val_loss:0.4624  Val_accuracy:0.7826
Epoch:35   Loss:0.4666  Accuracy:0.7803  Val_loss:0.4584  Val_accuracy:0.7835
Epoch:36   Loss:0.4627  Accuracy:0.7821  Val_loss:0.4551  Val_accuracy:0.7853
Epoch:37   Loss:0.4595  Accuracy:0.7839  Val_loss:0.4525  Val_accuracy:0.7906
Epoch:38   Loss:0.4570  Accuracy:0.7859  Val_loss:0.4504  Val_accuracy:0.7906
Epoch:39   Loss:0.4550  Accuracy:0.7861  Val_loss:0.4489  Val_accuracy:0.7933
Epoch:40   Loss:0.4535  Accuracy:0.7881  Val_loss:0.4477  Val_accuracy:0.7933
Epoch:41   Loss:0.4523  Accuracy:0.7881  Val_loss:0.4467  Val_accuracy:0.7941
Epoch:42   Loss:0.4513  Accuracy:0.7877  Val_loss:0.4458  Val_accuracy:0.7941
Epoch:43   Loss:0.4503  Accuracy:0.7888  Val_loss:0.4451  Val_accuracy:0.7915
Epoch:44   Loss:0.4494  Accuracy:0.7899  Val_loss:0.4443  Val_accuracy:0.7941
Epoch:45   Loss:0.4485  Accuracy:0.7894  Val_loss:0.4435  Val_accuracy:0.7924
Epoch:46   Loss:0.4476  Accuracy:0.7897  Val_loss:0.4426  Val_accuracy:0.7915
Epoch:47   Loss:0.4465  Accuracy:0.7881  Val_loss:0.4417  Val_accuracy:0.7879
Epoch:48   Loss:0.4454  Accuracy:0.7874  Val_loss:0.4407  Val_accuracy:0.7879
Epoch:49   Loss:0.4442  Accuracy:0.7866  Val_loss:0.4396  Val_accuracy:0.7844
Epoch:50   Loss:0.4429  Accuracy:0.7874  Val_loss:0.4386  Val_accuracy:0.7844
Epoch:51   Loss:0.4417  Accuracy:0.7866  Val_loss:0.4376  Val_accuracy:0.7835
Epoch:52   Loss:0.4405  Accuracy:0.7861  Val_loss:0.4366  Val_accuracy:0.7853
Epoch:53   Loss:0.4393  Accuracy:0.7857  Val_loss:0.4357  Val_accuracy:0.7799
Epoch:54   Loss:0.4382  Accuracy:0.7859  Val_loss:0.4348  Val_accuracy:0.7808
Epoch:55   Loss:0.4371  Accuracy:0.7859  Val_loss:0.4340  Val_accuracy:0.7791
Epoch:56   Loss:0.4361  Accuracy:0.7854  Val_loss:0.4332  Val_accuracy:0.7799
Epoch:57   Loss:0.4352  Accuracy:0.7848  Val_loss:0.4325  Val_accuracy:0.7791
Epoch:58   Loss:0.4344  Accuracy:0.7841  Val_loss:0.4319  Val_accuracy:0.7799
Epoch:59   Loss:0.4336  Accuracy:0.7843  Val_loss:0.4313  Val_accuracy:0.7808
Epoch:60   Loss:0.4329  Accuracy:0.7848  Val_loss:0.4307  Val_accuracy:0.7799
Epoch:61   Loss:0.4322  Accuracy:0.7850  Val_loss:0.4302  Val_accuracy:0.7835
Epoch:62   Loss:0.4315  Accuracy:0.7852  Val_loss:0.4297  Val_accuracy:0.7826
Epoch:63   Loss:0.4309  Accuracy:0.7850  Val_loss:0.4292  Val_accuracy:0.7826
Epoch:64   Loss:0.4303  Accuracy:0.7850  Val_loss:0.4287  Val_accuracy:0.7844
Epoch:65   Loss:0.4297  Accuracy:0.7854  Val_loss:0.4282  Val_accuracy:0.7862
Epoch:66   Loss:0.4291  Accuracy:0.7872  Val_loss:0.4277  Val_accuracy:0.7879
Epoch:67   Loss:0.4284  Accuracy:0.7874  Val_loss:0.4272  Val_accuracy:0.7879
Epoch:68   Loss:0.4278  Accuracy:0.7881  Val_loss:0.4266  Val_accuracy:0.7879
Epoch:69   Loss:0.4272  Accuracy:0.7881  Val_loss:0.4261  Val_accuracy:0.7879
Epoch:70   Loss:0.4266  Accuracy:0.7888  Val_loss:0.4255  Val_accuracy:0.7870
Epoch:71   Loss:0.4260  Accuracy:0.7910  Val_loss:0.4250  Val_accuracy:0.7870
Epoch:72   Loss:0.4254  Accuracy:0.7912  Val_loss:0.4245  Val_accuracy:0.7879
Epoch:73   Loss:0.4248  Accuracy:0.7905  Val_loss:0.4239  Val_accuracy:0.7888
Epoch:74   Loss:0.4241  Accuracy:0.7901  Val_loss:0.4234  Val_accuracy:0.7888
Epoch:75   Loss:0.4235  Accuracy:0.7903  Val_loss:0.4229  Val_accuracy:0.7924
Epoch:76   Loss:0.4229  Accuracy:0.7921  Val_loss:0.4224  Val_accuracy:0.7968
Epoch:77   Loss:0.4223  Accuracy:0.7925  Val_loss:0.4219  Val_accuracy:0.7968
Epoch:78   Loss:0.4217  Accuracy:0.7919  Val_loss:0.4214  Val_accuracy:0.7968
Epoch:79   Loss:0.4211  Accuracy:0.7923  Val_loss:0.4209  Val_accuracy:0.7941
Epoch:80   Loss:0.4205  Accuracy:0.7934  Val_loss:0.4205  Val_accuracy:0.7950
Epoch:81   Loss:0.4199  Accuracy:0.7934  Val_loss:0.4201  Val_accuracy:0.7950
Epoch:82   Loss:0.4194  Accuracy:0.7932  Val_loss:0.4197  Val_accuracy:0.7941
Epoch:83   Loss:0.4188  Accuracy:0.7930  Val_loss:0.4193  Val_accuracy:0.7941
Epoch:84   Loss:0.4183  Accuracy:0.7930  Val_loss:0.4190  Val_accuracy:0.7941
Epoch:85   Loss:0.4178  Accuracy:0.7925  Val_loss:0.4186  Val_accuracy:0.7933
Epoch:86   Loss:0.4172  Accuracy:0.7925  Val_loss:0.4183  Val_accuracy:0.7933
Epoch:87   Loss:0.4167  Accuracy:0.7919  Val_loss:0.4180  Val_accuracy:0.7941
Epoch:88   Loss:0.4162  Accuracy:0.7919  Val_loss:0.4177  Val_accuracy:0.7950
Epoch:89   Loss:0.4157  Accuracy:0.7917  Val_loss:0.4174  Val_accuracy:0.7959
Epoch:90   Loss:0.4152  Accuracy:0.7930  Val_loss:0.4172  Val_accuracy:0.7959
Epoch:91   Loss:0.4147  Accuracy:0.7932  Val_loss:0.4169  Val_accuracy:0.7959
Epoch:92   Loss:0.4142  Accuracy:0.7937  Val_loss:0.4167  Val_accuracy:0.7959
Epoch:93   Loss:0.4136  Accuracy:0.7950  Val_loss:0.4165  Val_accuracy:0.7959
Epoch:94   Loss:0.4131  Accuracy:0.7959  Val_loss:0.4163  Val_accuracy:0.7977
Epoch:95   Loss:0.4127  Accuracy:0.7961  Val_loss:0.4161  Val_accuracy:0.7977
Epoch:96   Loss:0.4122  Accuracy:0.7968  Val_loss:0.4160  Val_accuracy:0.7986
Epoch:97   Loss:0.4117  Accuracy:0.7974  Val_loss:0.4158  Val_accuracy:0.7995
Epoch:98   Loss:0.4113  Accuracy:0.7974  Val_loss:0.4157  Val_accuracy:0.7995
Epoch:99   Loss:0.4108  Accuracy:0.7972  Val_loss:0.4156  Val_accuracy:0.8012
Test Loss: 0.43
Test Accuracy:0.78

In [17]:
from sklearn.metrics import confusion_matrix

print(confusion_matrix(y_test,fin_prob))

[[854 181]
 [133 241]]

In [18]:
from sklearn.metrics import classification_report
print(classification_report(y_test,fin_prob))

              precision    recall  f1-score   support

         0.0       0.87      0.83      0.84      1035
         1.0       0.57      0.64      0.61       374

    accuracy                           0.78      1409
   macro avg       0.72      0.73      0.73      1409
weighted avg       0.79      0.78      0.78      1409